routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','users/login');

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/','users/login');
    Route::match(['get', 'post'],'register', 'register')->name('register');
    Route::match(['get', 'post'],'login', 'login')->name('login');
    Route::match(['get', 'post'],'logout', 'logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function (){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('getExaminationsCount', 'getExaminationsCount')->name('getExaminationsCount');
        Route::get('getExaminationsPassingRate','getExaminationsPassingRate')->name('getExaminationsPassingRate');
        Route::get('getExaminationsMostTake','getExaminationsMostTake')->name('getExaminationsMostTake');
        Route::get('getLeaderboardsWeek','getLeaderboardsWeek')->name('getLeaderboardsWeek');
        Route::get('getLeaderboardsMonth','getLeaderboardsMonth')->name('getLeaderboardsMonth');
        Route::get('getLeaderboardsYear','getLeaderboardsYear')->name('getLeaderboardsYear');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
    });

    Route::group(['controller' => 'SectionsController', 'prefix' => 'sections', 'as' => 'sections.'], function (){
        Route::redirect('/','sections/index');
        Route::get('index','index')->name('index');
        Route::get('getSections','getSections')->name('getSections');
        Route::get('bin','bin')->name('bin');
        Route::get('getSectionsDeleted','getSectionsDeleted')->name('getSectionsDeleted');
        Route::get('getSectionsList/{examId}','getSectionsList')->name('getSectionsList');
        Route::get('getSectionsExamList/{examId}','getSectionsExamList')->name('getSectionsExamList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ReviewersController', 'prefix' => 'reviewers', 'as' => 'reviewers.'], function (){
        Route::redirect('/','reviewers/index');
        Route::get('index','index')->name('index');
        Route::get('getReviewers','getReviewers')->name('getReviewers');
        Route::get('bin','bin')->name('bin');
        Route::get('getReviewersDeleted','getReviewersDeleted')->name('getReviewersDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'QuestionsController', 'prefix' => 'questions', 'as' => 'questions.'], function (){
        Route::redirect('/','questions/index');
        Route::get('index','index')->name('index');
        Route::get('getQuestions','getQuestions')->name('getQuestions');
        Route::get('bin','bin')->name('bin');
        Route::get('getQuestionsDeleted','getQuestionsDeleted')->name('getQuestionsDeleted');
        Route::get('getQuestionsSectionList/{sectionId}','getQuestionsSectionList')->name('getQuestionsSectionList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'LessonsController', 'prefix' => 'lessons', 'as' => 'lessons.'], function (){
        Route::redirect('/','lessons/index');
        Route::get('index','index')->name('index');
        Route::get('getLessons','getLessons')->name('getLessons');
        Route::get('bin','bin')->name('bin');
        Route::get('getLessonsDeleted','getLessonsDeleted')->name('getLessonsDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'download/{id}', 'download')->name('download');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExamsController', 'prefix' => 'exams', 'as' => 'exams.'], function (){
        Route::redirect('/','exams/index');
        Route::get('index','index')->name('index');
        Route::get('getExams','getExams')->name('getExams');
        Route::get('bin','bin')->name('bin');
        Route::get('getExamsDeleted','getExamsDeleted')->name('getExamsDeleted');
        Route::get('getExam/{id}','getExam')->name('getExam');
        Route::get('practice','practice')->name('practice');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExaminationsController', 'prefix' => 'examinations', 'as' => 'examinations.'], function (){
        Route::redirect('/','examinations/index');
        Route::get('index','index')->name('index');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('today','today')->name('today');
        Route::get('getExaminationsToday','getExaminationsToday')->name('getExaminationsToday');
        Route::get('week','week')->name('week');
        Route::get('getExaminationsWeek','getExaminationsWeek')->name('getExaminationsWeek');
        Route::get('month','month')->name('month');
        Route::get('getExaminationsMonth','getExaminationsMonth')->name('getExaminationsMonth');
        Route::get('year','year')->name('year');
        Route::get('getExaminationsYear','getExaminationsYear')->name('getExaminationsYear');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'exam/{id}/{examId}', 'exam')->name('exam');
        Route::match(['get', 'post'],'release/{id}', 'release')->name('release');
        Route::get('counts/{userId}', 'counts')->name('counts');
        Route::get('getAnswersStatistics/{userId}', 'getAnswersStatistics')->name('getAnswersStatistics');
        Route::get('getAverage/{userId}', 'getAverage')->name('getAverage');
    });

    Route::group(['controller' => 'DocumentsController', 'prefix' => 'documents', 'as' => 'documents.'], function (){
        Route::redirect('/','documents/index');
        Route::get('index','index')->name('index');
        Route::get('getDocuments','getDocuments')->name('getDocuments');
        Route::get('bin','bin')->name('bin');
        Route::get('getDocumentsDeleted','getDocumentsDeleted')->name('getDocumentsDeleted');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;
use YoHang88\LetterAvatar\LetterAvatar;

class User extends Authenticatable
{
    use HasFactory, SoftDeletes;

    protected $table = 'users';

    protected static function booted(): void
    {
        static::saved(function (User $user) {

            try{

                $path = public_path('img/user-avatar');
                $folder = File::isDirectory($path);
                if(!$folder){
                    File::makeDirectory($path);
                }

                $filepath = public_path('img/user-avatar/'.(strval($user->attributes['id'])).'.png');

                $avatar = new LetterAvatar(strtoupper($user->attributes['name']), 'circle', 200);

                $avatar->setColor('#339598', '#ffffff');

                $avatar->saveAs($filepath, LetterAvatar::MIME_TYPE_PNG);

            }catch (\Exception $exception){

            }

        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'contact_number',
        'password',
        'is_admin',
        'is_examinee',
        'is_active',
        'token',
        'remember_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'token',
        'remember_token',
    ];

    protected function setNameAttribute($value){
        return $this->attributes['name'] = strtoupper($value);
    }

    protected function setPasswordAttribute($value){
        return $this->attributes['password'] = Hash::make($value);
    }

    public function Sections(){
        return $this->hasMany(Section::class,'user_id', 'id');
    }

    public function Reviewers(){
        return $this->hasMany(Reviewer::class,'user_id', 'id');
    }

    public function Questions(){
        return $this->hasMany(Question::class,'user_id', 'id');
    }

    public function Lessons(){
        return $this->hasMany(Lesson::class,'user_id', 'id');
    }

    public function Examinations(){
        return $this->hasMany(Examination::class,'user_id', 'id');
    }

    public function Exams(){
        return $this->hasMany(Exam::class,'user_id', 'id');
    }

    public function Documents(){
        return $this->hasMany(Document::class,'user_id', 'id');
    }

    public function Answers(){
        return $this->hasMany(Answer::class,'user_id', 'id');
    }

}

resources/views/Users/login.blade.php
@extends('layout.default')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <form class="col-lg-3 col-md-4 col-10 mx-auto text-center" id="form" method="post" enctype="multipart/form-data">
        @csrf
        <div class="card shadow mb-4">
            <div class="card-header">
                <strong class="card-title">
                    <a class="navbar-brand mx-auto mt-2 flex-fill text-center" href="javascript:void(0);">
                        <svg version="1.1" id="logo" class="navbar-brand-img brand-md" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 120 120" xml:space="preserve">
              <g>
                  <polygon class="st0" points="78,105 15,105 24,87 87,87 	"></polygon>
                  <polygon class="st0" points="96,69 33,69 42,51 105,51 	"></polygon>
                  <polygon class="st0" points="78,33 15,33 24,15 87,15 	"></polygon>
              </g>
            </svg>
                    </a>
                </strong>
            </div>
            <div class="card-body">
                <h4 class="mb-3">Sign in</h4>
                <div class="form-group">
                    <label for="username" class="sr-only">Username | Email</label>
                    <input type="text" name="username" id="username" class="form-control form-control-lg required" placeholder="Username | Email" pattern="(.){1,}" title="{{ucwords('please fill out this field')}}" required>
                    <small></small>
                </div>
                <div class="form-group">
                    <label for="password" class="sr-only">Password</label>
                    <input type="password" name="password" id="password" class="form-control form-control-lg required" placeholder="Password" pattern="(.){1,}" title="{{ucwords('please fill out this field')}}" required>
                    <small></small>
                </div>
                <div class="form-group d-flex flex-nowrap justify-content-between align-items-center">
                    <div class="icheck-primary checkbox mb-3">
                        <input type="checkbox" name="remember_me" id="remember-me">
                        <label for="remember-me">Remember Me</label>
                    </div>
                    <div class="icheck-primary checkbox mb-3">
                        <input type="checkbox" name="show_password" id="show-password">
                        <label for="show-password">Show Password</label>
                    </div>
                </div>
                <button class="btn btn-lg btn-primary btn-block mt-3" type="submit">Sign In</button>
                <p class="mt-5 mb-3 text-muted">© 2024</p>
            </div>
            <div class="card-footer">
                <a href="{{route('users.register')}}" class="text-dark" turbo-links>Register</a>
            </div>
        </div>
    </form>

    <script src="{{url('public/js/users/login.js')}}"></script>
@endsection

resources/views/Users/register.blade.php
@extends('layout.default')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')

    <form class="col-sm-12 col-md-8 col-lg-5 col-10 mx-auto" id="form" method="post" enctype="multipart/form-data" style="overflow-y: auto !important;">
        @csrf
        <div class="card shadow mb-4">
            <div class="card-header text-center">
                <strong class="card-title">
                    <a class="navbar-brand mx-auto mt-2 flex-fill text-center" href="javascript:void(0);">
                        <svg version="1.1" id="logo" class="navbar-brand-img brand-md" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 120 120" xml:space="preserve">
              <g>
                  <polygon class="st0" points="78,105 15,105 24,87 87,87 	"></polygon>
                  <polygon class="st0" points="96,69 33,69 42,51 105,51 	"></polygon>
                  <polygon class="st0" points="78,33 15,33 24,15 87,15 	"></polygon>
              </g>
            </svg>
                    </a>
                </strong>
            </div>
            <div class="card-body">
                <h4 class="mb-3 text-center">Register</h4>
                <div class="row">
                    <div class="form-group col-sm-12 col-md-8 col-lg-8 my-2">
                        <label for="name">Name</label>
                        <input type="text" name="name" class="form-control rounded-0 required" id="name" placeholder="Name" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" required>
                        <small></small>
                    </div>

                    <div class="form-group col-sm-12 col-md-4 col-lg-4 my-2">
                        <label for="username">Username</label>
                        <input type="text" name="username" class="form-control rounded-0 required" id="username" placeholder="Username" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d).{8,24}" required>
                        <small></small>
                    </div>

                    <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                        <label for="email">Email</label>
                        <input type="email" name="email" class="form-control rounded-0 required" id="email" placeholder="Email" title="{{ucwords('please fill out this field')}}" pattern="\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+" required>
                        <small></small>
                    </div>

                    <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                        <label for="contact-number">Contact Number</label>
                        <input type="text" name="contact_number" class="form-control rounded-0 required" id="contact-number" placeholder="Contact Number" title="{{ucwords('please fill out this field')}}" pattern="(09|\+639)([0-9]{9})" required>
                        <small></small>
                    </div>

                    <div class="col-sm-12 col-md-7 col-lg-8">
                        <div class="row">
                            <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                                <label for="password">Password</label>
                                <input type="password" name="password" class="form-control rounded-0 required" id="password" placeholder="Password" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':&quot;\\|,.<>\/?]).{8,}" required>
                                <small></small>
                            </div>

                            <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                                <label for="confirm-password">Password (Confirm)</label>
                                <input type="password" name="confirm_password" class="form-control rounded-0 required" id="confirm-password" placeholder="Password (Confirm)" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':&quot;\\|,.<>\/?]).{8,}" required>
                                <small></small>
                            </div>

                            <div class="form-group col-sm-12 col-md-12 col-lg-12 my-1">
                                <div class="icheck-primary">
                                    <input type="checkbox" id="show-password">
                                    <label for="show-password">Show Password</label>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12 col-md-5 col-lg-4 text-capitalize my-2">
                        <p class="mb-2">Password requirements</p>
                        <p class="small text-muted mb-2 text-dark"> To create a new password, you have to meet all of the following requirements: </p>
                        <ul class="small text-muted pl-4 mb-0 text-dark">
                            <li> Minimum 8 character </li>
                            <li>At least one special character</li>
                            <li>At least one number</li>
                            <li>Can’t be the same as a previous password </li>
                        </ul>
                    </div>

                    <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                        <input type="hidden" name="is_active" id="is-active" value="1" required>
                        <input type="hidden" name="is_admin" id="is-admin" value="0" required>
                        <input type="hidden" name="is_examinee" id="is-examinee" value="1" required>
                        <input type="hidden" name="token" id="token" value="{{uniqid()}}" required>
                        <button type="submit" class="btn btn-primary btn-block">Submit</button>
                    </div>
                </div>
            </div>
            <div class="card-footer text-center">
                <a href="{{route('users.login')}}" class="text-dark" turbo-links>Return To Login</a>
            </div>
        </div>
    </form>

    <script src="{{url('public/js/users/register.js')}}"></script>
@endsection