routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','users/login');

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/','users/login');
    Route::match(['get', 'post'],'register', 'register')->name('register');
    Route::match(['get', 'post'],'login', 'login')->name('login');
    Route::match(['get', 'post'],'logout', 'logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function (){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('getExaminationsCount', 'getExaminationsCount')->name('getExaminationsCount');
        Route::get('getExaminationsPassingRate','getExaminationsPassingRate')->name('getExaminationsPassingRate');
        Route::get('getExaminationsMostTake','getExaminationsMostTake')->name('getExaminationsMostTake');
        Route::get('getLeaderboardsWeek','getLeaderboardsWeek')->name('getLeaderboardsWeek');
        Route::get('getLeaderboardsMonth','getLeaderboardsMonth')->name('getLeaderboardsMonth');
        Route::get('getLeaderboardsYear','getLeaderboardsYear')->name('getLeaderboardsYear');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
    });

    Route::group(['controller' => 'SectionsController', 'prefix' => 'sections', 'as' => 'sections.'], function (){
        Route::redirect('/','sections/index');
        Route::get('index','index')->name('index');
        Route::get('getSections','getSections')->name('getSections');
        Route::get('bin','bin')->name('bin');
        Route::get('getSectionsDeleted','getSectionsDeleted')->name('getSectionsDeleted');
        Route::get('getSectionsList/{examId}','getSectionsList')->name('getSectionsList');
        Route::get('getSectionsExamList/{examId}','getSectionsExamList')->name('getSectionsExamList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ReviewersController', 'prefix' => 'reviewers', 'as' => 'reviewers.'], function (){
        Route::redirect('/','reviewers/index');
        Route::get('index','index')->name('index');
        Route::get('getReviewers','getReviewers')->name('getReviewers');
        Route::get('bin','bin')->name('bin');
        Route::get('getReviewersDeleted','getReviewersDeleted')->name('getReviewersDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'QuestionsController', 'prefix' => 'questions', 'as' => 'questions.'], function (){
        Route::redirect('/','questions/index');
        Route::get('index','index')->name('index');
        Route::get('getQuestions','getQuestions')->name('getQuestions');
        Route::get('bin','bin')->name('bin');
        Route::get('getQuestionsDeleted','getQuestionsDeleted')->name('getQuestionsDeleted');
        Route::get('getQuestionsSectionList/{sectionId}','getQuestionsSectionList')->name('getQuestionsSectionList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'LessonsController', 'prefix' => 'lessons', 'as' => 'lessons.'], function (){
        Route::redirect('/','lessons/index');
        Route::get('index','index')->name('index');
        Route::get('getLessons','getLessons')->name('getLessons');
        Route::get('bin','bin')->name('bin');
        Route::get('getLessonsDeleted','getLessonsDeleted')->name('getLessonsDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'download/{id}', 'download')->name('download');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExamsController', 'prefix' => 'exams', 'as' => 'exams.'], function (){
        Route::redirect('/','exams/index');
        Route::get('index','index')->name('index');
        Route::get('getExams','getExams')->name('getExams');
        Route::get('bin','bin')->name('bin');
        Route::get('getExamsDeleted','getExamsDeleted')->name('getExamsDeleted');
        Route::get('getExam/{id}','getExam')->name('getExam');
        Route::get('practice','practice')->name('practice');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExaminationsController', 'prefix' => 'examinations', 'as' => 'examinations.'], function (){
        Route::redirect('/','examinations/index');
        Route::get('index','index')->name('index');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('today','today')->name('today');
        Route::get('getExaminationsToday','getExaminationsToday')->name('getExaminationsToday');
        Route::get('week','week')->name('week');
        Route::get('getExaminationsWeek','getExaminationsWeek')->name('getExaminationsWeek');
        Route::get('month','month')->name('month');
        Route::get('getExaminationsMonth','getExaminationsMonth')->name('getExaminationsMonth');
        Route::get('year','year')->name('year');
        Route::get('getExaminationsYear','getExaminationsYear')->name('getExaminationsYear');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'exam/{id}/{examId}', 'exam')->name('exam');
        Route::match(['get', 'post'],'release/{id}', 'release')->name('release');
        Route::get('counts/{userId}', 'counts')->name('counts');
        Route::get('getAnswersStatistics/{userId}', 'getAnswersStatistics')->name('getAnswersStatistics');
        Route::get('getAverage/{userId}', 'getAverage')->name('getAverage');
    });

    Route::group(['controller' => 'DocumentsController', 'prefix' => 'documents', 'as' => 'documents.'], function (){
        Route::redirect('/','documents/index');
        Route::get('index','index')->name('index');
        Route::get('getDocuments','getDocuments')->name('getDocuments');
        Route::get('bin','bin')->name('bin');
        Route::get('getDocumentsDeleted','getDocumentsDeleted')->name('getDocumentsDeleted');

app/Models/Exam.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Exam extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'exams';

    protected $fillable = [
        'user_id',
        'exam',
        'minutes',
        'month',
        'year',
        'content',
        'total',
        'average',
        'is_active'
    ];

    protected function setExamAttribute($value){
        return $this->attributes['exam'] = strtoupper($value);
    }

    protected function setMinutesAttribute($value){
        return $this->attributes['minutes'] = intval($value);
    }

    protected function setMonthAttribute($value){
        return $this->attributes['month'] = strtoupper($value);
    }

    public function Users(){
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function Sections(){
        return $this->hasMany(Section::class,'exam_id','id');
    }

    public function Questions(){
        return $this->hasMany(Question::class,'exam_id','id');
    }

    public function Examinations(){
        return $this->hasMany(Examination::class,'exam_id','id');
    }

}

app/Http/Controllers/Examinee/ExamsController.php
<?php

namespace App\Http\Controllers\Examinee;

use App\Http\Controllers\Controller;
use App\Models\Exam;
use App\Models\Examination;
use App\Models\Question;
use App\Models\Reviewer;
use App\Models\Section;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Illuminate\Validation\Rule;
use Moment\Moment;

class ExamsController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request){
        $this->authorize('examinee', Exam::class);
        $now = (new Moment(null,'Asia/Manila'))->format('Y-m-d H:i:s');
        $exams = Exam::withoutTrashed()
            ->select('exams.*')
            ->with([
                'Users' => function($query){
                    return $query->withTrashed()->get();
                },
                'Sections' => function($query){
                    return $query->withTrashed()
                        ->where([
                            ['sections.is_active', '=', intval(1)]
                        ])->get();
                },
                'Sections.Reviewers' => function($query){
                    return $query->withTrashed()->get();
                },
                'Sections.Questions' => function($query){
                    return $query->withTrashed()
                        ->where([
                            ['questions.is_active', '=', intval(1)]
                        ])->get();
                },
                'Questions' => function($query){
                    return $query->withoutTrashed()
                        ->where([
                            ['questions.is_active', '=', intval(1)]
                        ])->get();
                },
            ])
            ->leftJoin('examinations', function($query) use($now){
                return $query->on('exams.id', '=', 'examinations.exam_id')
                    ->where('examinations.user_id', '=', intval(auth()->user()->id))
                    ->where('examinations.start_date', '<=', $now)
                    ->where('examinations.end_date', '>=', $now)
                    ->where('examinations.is_released', '=', intval(0));
            })
            ->selectRaw('examinations.id as examination_id')
            ->where([
                ['exams.is_active', '=', intval(1)]
            ])
            ->orderBy('exams.created_at','ASC')
            ->paginate(intval(100))
            ->withQueryString()
            ->appends($request->query());
        return view('Examinee.Exams.index', compact('exams'));
    }

    public function getExam($id = null){
        $this->authorize('examinee', Exam::class);
        $exam = Exam::withoutTrashed()->findOrFail($id);
        return response()->json($exam);
    }
}

resources/views/Admin/Exams/add.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')


    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <a href="{{route('admin.exams.index')}}" id="toggle-modal" class="btn btn-secondary rounded-0" title="{{ucwords('Return')}}" turbo-links>Return</a>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-header">
                    <strong class="card-title">Form</strong>
                </div>
                <div class="card-body">
                    <form action="" class="row" id="form" method="post" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <label for="exam">Exam</label>
                            <input type="text" name="exam" class="form-control rounded-0 required" id="exam" placeholder="Exam" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-2 col-lg-2 my-2">
                            <label for="month">Month</label>
                            <input type="text" name="month" class="form-control rounded-0 required" id="month" placeholder="Month" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{date('F')}}" readonly required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-2 col-lg-1 my-2">
                            <label for="year">Year</label>
                            <input type="text" name="year" class="form-control rounded-0 required" id="year" placeholder="Year" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{date('Y')}}" readonly required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-2 col-lg-1 my-2">
                            <label for="minutes">Minutes</label>
                            <input type="number" name="minutes" class="form-control rounded-0 required" id="minutes" placeholder="Minutes" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="15" step="any" min="15" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-3 col-lg-4 my-2">
                            <label for="total">Total</label>
                            <input type="number" name="total" class="form-control rounded-0 required" id="total" placeholder="Total" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="1" step="any" min="1" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-3 col-lg-4 my-2">
                            <label for="average">Average</label>
                            <input type="number" name="average" class="form-control rounded-0 required" id="average" placeholder="Average" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="1" step="any" min="1" max="100" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <label for="content">Content</label>
                            <textarea name="content" class="form-control rounded-0 required" id="content" placeholder="Content" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}"></textarea>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2 d-flex justify-content-start align-items-center">
                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="active" checked>
                                <label for="active">Active</label>
                            </div>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <input type="hidden" name="user_id" id="user-id" value="<?=intval(auth()->user()->id)?>" required>
                            <input type="hidden" name="is_active" id="is-active" value="1" required>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-danger">Reset</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/exams/add.js')}}"></script>
@endsection

resources/views/Admin/Exams/view.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')

    <?php
       $content = '';
       $path = public_path($exam->content);
       $folder = \Illuminate\Support\Facades\File::isFile($path);
       if($folder){
           $content = file_get_contents($path);
       }
    ?>

    <script>
        var id = parseInt({{intval($exam->id)}});
    </script>

    <div class="modal fade" id="modal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog modal-xl" role="document">
            <form class="modal-content" id="section-form" method="post" enctype="multipart/form-data">
                @csrf
                <div class="modal-header">
                    <h5 class="modal-title">Section</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                    <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                        <label for="reviewer-id">Reviewer</label>
                        <select name="reviewer_id" class="form-control rounded-0 required" id="reviewer-id" title="{{ucwords('please fill out this field')}}" required>
                            <option value="">Select Reviewer</option>
                            @foreach($reviewers as $key => $value)
                                <option value="{{intval($key)}}">{{strtoupper($value)}}</option>
                            @endforeach
                        </select>
                        <small></small>
                    </div>

                    <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                        <label for="content">Content</label>
                        <textarea name="content" class="form-control rounded-0 required" id="section-content" placeholder="Content" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}"></textarea>
                        <small></small>
                    </div>

                    <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2 d-flex justify-content-start align-items-center">
                        <div class="icheck-primary m-2">
                            <input type="checkbox" id="section-active" checked>
                            <label for="section-active">Active</label>
                        </div>
                    </div>

                </div>
                <div class="modal-footer">
                    <input type="hidden" name="exam_id" id="exam-id" value="{{intval($exam->id)}}" required>
                    <input type="hidden" name="user_id" id="user-id" value="<?=intval(auth()->user()->id)?>" required>
                    <input type="hidden" name="order_position" id="order-position" value="0" required>
                    <input type="hidden" name="is_active" id="section-is-active" value="1" required>
                    <button type="reset" class="btn mb-2 btn-danger">Reset</button>
                    <button type="submit" class="btn mb-2 btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <button type="button" id="toggle-modal" class="btn btn-primary rounded-0 mr-2" title="{{ucwords('New Section')}}">New Section</button>
            <a href="{{route('admin.exams.index')}}" class="btn btn-secondary rounded-0" title="{{ucwords('Return')}}" turbo-links>Return</a>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8">
            <div class="row justify-content-center">
                <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
                    <div class="card shadow">
                        <div class="card-header">
                            <strong class="card-title">Form</strong>
                        </div>
                        <div class="card-body">
                            <form action="" class="row" id="form" method="post" enctype="multipart/form-data">
                                @csrf

                                <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                                    <label for="exam">Exam</label>
                                    <input type="text" name="exam" class="form-control rounded-0 required" id="exam" placeholder="Exam" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{$exam->exam}}" required>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-4 col-lg-4 my-2">
                                    <label for="month">Month</label>
                                    <input type="text" name="month" class="form-control rounded-0 required" id="month" placeholder="Month" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{$exam->month}}" readonly required>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-4 col-lg-4 my-2">
                                    <label for="year">Year</label>
                                    <input type="text" name="year" class="form-control rounded-0 required" id="year" placeholder="Year" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{$exam->year}}" readonly required>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-4 col-lg-4 my-2">
                                    <label for="minutes">Minutes</label>
                                    <input type="number" name="minutes" class="form-control rounded-0 required" id="minutes" placeholder="Minutes" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{intval($exam->minutes)}}" step="any" min="15" required>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-6 col-lg-5 my-2">
                                    <label for="total">Total</label>
                                    <input type="number" name="total" class="form-control rounded-0 required" id="total" placeholder="Total" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{$exam->total}}" step="any" min="1" required>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-6 col-lg-5 my-2">
                                    <label for="average">Average</label>
                                    <input type="number" name="average" class="form-control rounded-0 required" id="average" placeholder="Average" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{$exam->average}}" step="any" min="1" max="100" required>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                                    <label for="content">Content</label>
                                    <textarea name="content" class="form-control rounded-0 required" id="content" placeholder="Content" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}"><?=$content?></textarea>
                                    <small></small>
                                </div>

                                <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2 d-flex justify-content-start align-items-center">
                                    <div class="icheck-primary m-2">
                                        <input type="checkbox" id="active" {{(boolval($exam->is_active))? 'checked': null;}}>
                                        <label for="active">Active</label>
                                    </div>
                                </div>

                                <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                                    <input type="hidden" name="user_id" id="user-id" value="<?=intval(auth()->user()->id)?>" required>
                                    <input type="hidden" name="is_active" id="is-active" value="{{intval($exam->is_active)}}" required>
                                    <button type="submit" class="btn btn-primary">Submit</button>
                                    <button type="reset" class="btn btn-danger">Reset</button>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-5 col-lg-4">
            <div class="row">
                <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
                    <div class="accordion w-100" id="section-accordion">
                        @foreach($sections as $key => $section)
                            <div class="card shadow order-position" data-id="{{intval($section['id'])}}">
                                <div class="card-header" id="heading-{{$section['id']}}">
                                    <a role="button" href="#collapse-{{$section['id']}}" data-toggle="collapse" data-target="#collapse-{{$section['id']}}" aria-expanded="false" aria-controls="collapse-{{$section['id']}}" class="collapsed float-left">
                                        <strong class="text-uppercase">
                                            <span class="section-no">{{$section['order_position']}}) </span>
                                            {{strtoupper($section['reviewers']['reviewer'])}}
                                        </strong>
                                    </a>
                                    <a href="{{route('admin.sections.view',['id' => intval($section['id'])])}}" class="float-right" target="_blank">
                                        <strong>
                                            <i class="fe fe-edit fe-16"></i>
                                        </strong>
                                    </a>
                                </div>
                                <div id="collapse-{{$section['id']}}" class="collapse" aria-labelledby="heading-{{$section['id']}}" data-parent="#section-accordion">
                                    <div class="card-body">
                                        <ol>
                                            @foreach($section['questions'] as $key => $question)
                                                <?php
                                                    $path = public_path($question['content']);
                                                    $folder = \Illuminate\Support\Facades\File::isFile($path);
                                                ?>
                                                @if($folder)
                                                        <li>
                                                            <?=file_get_contents($path);?> - <?=strtoupper($question['answer'])?>
                                                        </li>
                                                @endif
                                            @endforeach
                                        </ol>
                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/exams/view.js')}}"></script>
@endsection