routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','users/login');

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/','users/login');
    Route::match(['get', 'post'],'register', 'register')->name('register');
    Route::match(['get', 'post'],'login', 'login')->name('login');
    Route::match(['get', 'post'],'logout', 'logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function (){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('getExaminationsCount', 'getExaminationsCount')->name('getExaminationsCount');
        Route::get('getExaminationsPassingRate','getExaminationsPassingRate')->name('getExaminationsPassingRate');
        Route::get('getExaminationsMostTake','getExaminationsMostTake')->name('getExaminationsMostTake');
        Route::get('getLeaderboardsWeek','getLeaderboardsWeek')->name('getLeaderboardsWeek');
        Route::get('getLeaderboardsMonth','getLeaderboardsMonth')->name('getLeaderboardsMonth');
        Route::get('getLeaderboardsYear','getLeaderboardsYear')->name('getLeaderboardsYear');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
    });

    Route::group(['controller' => 'SectionsController', 'prefix' => 'sections', 'as' => 'sections.'], function (){
        Route::redirect('/','sections/index');
        Route::get('index','index')->name('index');
        Route::get('getSections','getSections')->name('getSections');
        Route::get('bin','bin')->name('bin');
        Route::get('getSectionsDeleted','getSectionsDeleted')->name('getSectionsDeleted');
        Route::get('getSectionsList/{examId}','getSectionsList')->name('getSectionsList');
        Route::get('getSectionsExamList/{examId}','getSectionsExamList')->name('getSectionsExamList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ReviewersController', 'prefix' => 'reviewers', 'as' => 'reviewers.'], function (){
        Route::redirect('/','reviewers/index');
        Route::get('index','index')->name('index');
        Route::get('getReviewers','getReviewers')->name('getReviewers');
        Route::get('bin','bin')->name('bin');
        Route::get('getReviewersDeleted','getReviewersDeleted')->name('getReviewersDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'QuestionsController', 'prefix' => 'questions', 'as' => 'questions.'], function (){
        Route::redirect('/','questions/index');
        Route::get('index','index')->name('index');
        Route::get('getQuestions','getQuestions')->name('getQuestions');
        Route::get('bin','bin')->name('bin');
        Route::get('getQuestionsDeleted','getQuestionsDeleted')->name('getQuestionsDeleted');
        Route::get('getQuestionsSectionList/{sectionId}','getQuestionsSectionList')->name('getQuestionsSectionList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'LessonsController', 'prefix' => 'lessons', 'as' => 'lessons.'], function (){
        Route::redirect('/','lessons/index');
        Route::get('index','index')->name('index');
        Route::get('getLessons','getLessons')->name('getLessons');
        Route::get('bin','bin')->name('bin');
        Route::get('getLessonsDeleted','getLessonsDeleted')->name('getLessonsDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'download/{id}', 'download')->name('download');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExamsController', 'prefix' => 'exams', 'as' => 'exams.'], function (){
        Route::redirect('/','exams/index');
        Route::get('index','index')->name('index');
        Route::get('getExams','getExams')->name('getExams');
        Route::get('bin','bin')->name('bin');
        Route::get('getExamsDeleted','getExamsDeleted')->name('getExamsDeleted');
        Route::get('getExam/{id}','getExam')->name('getExam');
        Route::get('practice','practice')->name('practice');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExaminationsController', 'prefix' => 'examinations', 'as' => 'examinations.'], function (){
        Route::redirect('/','examinations/index');
        Route::get('index','index')->name('index');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('today','today')->name('today');
        Route::get('getExaminationsToday','getExaminationsToday')->name('getExaminationsToday');
        Route::get('week','week')->name('week');
        Route::get('getExaminationsWeek','getExaminationsWeek')->name('getExaminationsWeek');
        Route::get('month','month')->name('month');
        Route::get('getExaminationsMonth','getExaminationsMonth')->name('getExaminationsMonth');
        Route::get('year','year')->name('year');
        Route::get('getExaminationsYear','getExaminationsYear')->name('getExaminationsYear');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'exam/{id}/{examId}', 'exam')->name('exam');
        Route::match(['get', 'post'],'release/{id}', 'release')->name('release');
        Route::get('counts/{userId}', 'counts')->name('counts');
        Route::get('getAnswersStatistics/{userId}', 'getAnswersStatistics')->name('getAnswersStatistics');
        Route::get('getAverage/{userId}', 'getAverage')->name('getAverage');
    });

    Route::group(['controller' => 'DocumentsController', 'prefix' => 'documents', 'as' => 'documents.'], function (){
        Route::redirect('/','documents/index');
        Route::get('index','index')->name('index');
        Route::get('getDocuments','getDocuments')->name('getDocuments');
        Route::get('bin','bin')->name('bin');
        Route::get('getDocumentsDeleted','getDocumentsDeleted')->name('getDocumentsDeleted');

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\File;
use Illuminate\Support\Facades\Hash;
use Laravel\Sanctum\HasApiTokens;
use YoHang88\LetterAvatar\LetterAvatar;

class User extends Authenticatable
{
    use HasFactory, SoftDeletes;

    protected $table = 'users';

    protected static function booted(): void
    {
        static::saved(function (User $user) {

            try{

                $path = public_path('img/user-avatar');
                $folder = File::isDirectory($path);
                if(!$folder){
                    File::makeDirectory($path);
                }

                $filepath = public_path('img/user-avatar/'.(strval($user->attributes['id'])).'.png');

                $avatar = new LetterAvatar(strtoupper($user->attributes['name']), 'circle', 200);

                $avatar->setColor('#339598', '#ffffff');

                $avatar->saveAs($filepath, LetterAvatar::MIME_TYPE_PNG);

            }catch (\Exception $exception){

            }

        });
    }

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'username',
        'email',
        'contact_number',
        'password',
        'is_admin',
        'is_examinee',
        'is_active',
        'token',
        'remember_token',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'token',
        'remember_token',
    ];

    protected function setNameAttribute($value){
        return $this->attributes['name'] = strtoupper($value);
    }

    protected function setPasswordAttribute($value){
        return $this->attributes['password'] = Hash::make($value);
    }

    public function Sections(){
        return $this->hasMany(Section::class,'user_id', 'id');
    }

    public function Reviewers(){
        return $this->hasMany(Reviewer::class,'user_id', 'id');
    }

    public function Questions(){
        return $this->hasMany(Question::class,'user_id', 'id');
    }

    public function Lessons(){
        return $this->hasMany(Lesson::class,'user_id', 'id');
    }

    public function Examinations(){
        return $this->hasMany(Examination::class,'user_id', 'id');
    }

    public function Exams(){
        return $this->hasMany(Exam::class,'user_id', 'id');
    }

    public function Documents(){
        return $this->hasMany(Document::class,'user_id', 'id');
    }

    public function Answers(){
        return $this->hasMany(Answer::class,'user_id', 'id');
    }

}

resources/views/Admin/Users/add.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <a href="{{route('admin.users.index')}}" id="toggle-modal" class="btn btn-secondary rounded-0" title="{{ucwords('Return')}}" turbo-links>Return</a>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-header">
                    <strong class="card-title">Form</strong>
                </div>
                <div class="card-body">
                    <form action="" class="row" id="form" method="post" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control rounded-0 required" id="name" placeholder="Name" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                            <label for="username">Username</label>
                            <input type="text" name="username" class="form-control rounded-0 required" id="username" placeholder="Username" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d).{8,24}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control rounded-0 required" id="email" placeholder="Email" title="{{ucwords('please fill out this field')}}" pattern="\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                            <label for="password">Password</label>
                            <input type="password" name="password" class="form-control rounded-0 required" id="password" placeholder="Password" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':&quot;\\|,.<>\/?]).{8,}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                            <label for="confirm-password">Password (Confirm)</label>
                            <input type="password" name="confirm_password" class="form-control rounded-0 required" id="confirm-password" placeholder="Password (Confirm)" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*()_+\-=\[\]{};':&quot;\\|,.<>\/?]).{8,}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-1">
                            <div class="icheck-primary">
                                <input type="checkbox" id="show-password">
                                <label for="show-password">Show Password</label>
                            </div>
                        </div>

                        <div class="form-group col-sm-12 col-md-8 col-lg-7 my-2">
                            <label for="contact-number">Contact Number</label>
                            <input type="text" name="contact_number" class="form-control rounded-0 required" id="contact-number" placeholder="Contact Number" title="{{ucwords('please fill out this field')}}" pattern="(09|\+639)([0-9]{9})" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2 d-flex justify-content-start align-items-center">
                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="admin">
                                <label for="admin">Admin</label>
                            </div>

                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="examinee">
                                <label for="examinee">Examinee</label>
                            </div>

                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="active">
                                <label for="active">Active</label>
                            </div>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <input type="hidden" name="is_active" id="is-active" value="0" required>
                            <input type="hidden" name="is_admin" id="is-admin" value="1" required>
                            <input type="hidden" name="is_examinee" id="is-examinee" value="0" required>
                            <input type="hidden" name="token" id="token" value="{{uniqid()}}" required>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-danger">Reset</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/users/add.js')}}"></script>
@endsection

resources/views/Admin/Users/index.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <a href="{{route('admin.users.add')}}" id="toggle-modal" class="btn btn-secondary rounded-0" title="{{ucwords('New User')}}" turbo-links>New User</a>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-body">
                    <div class="table-responsive p-1">
                        <table id="datatable" class="table table table-hover dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Name</th>
                                <th>Username</th>
                                <th>Email</th>
                                <th>Contact Number</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/users/index.js')}}"></script>
@endsection

resources/views/Admin/Users/view.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <script>
        var id = parseInt(<?=intval($user->id)?>);
    </script>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <a href="{{route('admin.users.index')}}" id="toggle-modal" class="btn btn-secondary rounded-0" title="{{ucwords('Return')}}" turbo-links>Return</a>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-header">
                    <strong class="card-title">Form</strong>
                </div>
                <div class="card-body">
                    <form action="" class="row" id="form" method="post" enctype="multipart/form-data">
                        @csrf

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <label for="name">Name</label>
                            <input type="text" name="name" class="form-control rounded-0 required" id="name" placeholder="Name" title="{{ucwords('please fill out this field')}}" pattern="(.){1,}" value="{{$user->name}}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                            <label for="username">Username</label>
                            <input type="text" name="username" class="form-control rounded-0 required" id="username" placeholder="Username" title="{{ucwords('please fill out this field')}}" pattern="(?=.*[A-Z])(?=.*\d).{8,24}" value="{{$user->username}}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-6 col-lg-6 my-2">
                            <label for="email">Email</label>
                            <input type="email" name="email" class="form-control rounded-0 required" id="email" placeholder="Email" title="{{ucwords('please fill out this field')}}" pattern="\w+([\.-]?\w+)*@\w+([\.-]?\w+)*(\.\w{2,3})+" value="{{$user->email}}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-8 col-lg-7 my-2">
                            <label for="contact-number">Contact Number</label>
                            <input type="text" name="contact_number" class="form-control rounded-0 required" id="contact-number" placeholder="Contact Number" title="{{ucwords('please fill out this field')}}" pattern="(09|\+639)([0-9]{9})" value="{{$user->contact_number}}" required>
                            <small></small>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2 d-flex justify-content-start align-items-center">
                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="admin" <?=(boolval($user->is_admin))? 'checked': null?>>
                                <label for="admin">Admin</label>
                            </div>

                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="examinee" <?=(boolval($user->is_examinee))? 'checked': null?>>
                                <label for="examinee">Examinee</label>
                            </div>

                            <div class="icheck-primary m-2">
                                <input type="checkbox" id="active" <?=(boolval($user->is_active))? 'checked': null?>>
                                <label for="active">Active</label>
                            </div>
                        </div>

                        <div class="form-group col-sm-12 col-md-12 col-lg-12 my-2">
                            <input type="hidden" name="is_active" id="is-active" value="<?=intval($user->is_active)?>" required>
                            <input type="hidden" name="is_admin" id="is-admin" value="<?=intval($user->is_admin)?>" required>
                            <input type="hidden" name="is_examinee" id="is-examinee" value="<?=intval($user->is_examinee)?>" required>
                            <input type="hidden" name="token" id="token" value="{{uniqid()}}" required>
                            <button type="submit" class="btn btn-primary">Submit</button>
                            <button type="reset" class="btn btn-danger">Reset</button>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-4 col-lg-4 my-2">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-3 text-center">
                          <span class="circle circle-md bg-primary">
                            <span class="fe fe-file-text fe-24 text-white"></span>
                          </span>
                        </div>
                        <div class="col">
                            <h3 class="h6 mb-0 text-uppercase">Examinations (Total)</h3>
                            <p class="small text-muted mb-0" id="total-examinations">0</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 my-2">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-3 text-center">
                          <span class="circle circle-md bg-success">
                            <span class="fe fe-file-text fe-24 text-white"></span>
                          </span>
                        </div>
                        <div class="col">
                            <h3 class="h6 mb-0 text-uppercase">Examinations (Released)</h3>
                            <p class="small text-muted mb-0" id="total-released-examinations">0</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 my-2">
            <div class="card shadow mb-4">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-3 text-center">
                          <span class="circle circle-md bg-danger">
                            <span class="fe fe-file-text fe-24 text-white"></span>
                          </span>
                        </div>
                        <div class="col">
                            <h3 class="h6 mb-0 text-uppercase">Examinations (Not Released)</h3>
                            <p class="small text-muted mb-0" id="total-not-released-examinations">0</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-12 col-md-7 col-lg-8 my-2">
            <div class="card shadow eq-card mb-4">
                <div class="card-header">
                    <strong>Statistics</strong>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12" style="height: 55vh !important;">
                            <canvas id="examination-chart"></canvas>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-sm-12 col-md-5 col-lg-4 my-2">
            <div class="card shadow eq-card mb-4">
                <div class="card-header">
                    <strong>Passing Rate</strong>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-center align-items-center" style="height: 55vh !important;">
                            <div id="percircle" class="percircle green big">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/users/view.js')}}"></script>
@endsection