routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::redirect('/','users/login');

Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function(){
    Route::redirect('/','users/login');
    Route::match(['get', 'post'],'register', 'register')->name('register');
    Route::match(['get', 'post'],'login', 'login')->name('login');
    Route::match(['get', 'post'],'logout', 'logout')->name('logout');
});

Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth', 'admin']], function (){

    Route::redirect('/','admin/dashboards/index');

    Route::group(['controller' => 'DashboardsController', 'prefix' => 'dashboards', 'as' => 'dashboards.'], function (){
        Route::redirect('/','dashboards/index');
        Route::get('index','index')->name('index');
        Route::get('counts','counts')->name('counts');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('getExaminationsCount', 'getExaminationsCount')->name('getExaminationsCount');
        Route::get('getExaminationsPassingRate','getExaminationsPassingRate')->name('getExaminationsPassingRate');
        Route::get('getExaminationsMostTake','getExaminationsMostTake')->name('getExaminationsMostTake');
        Route::get('getLeaderboardsWeek','getLeaderboardsWeek')->name('getLeaderboardsWeek');
        Route::get('getLeaderboardsMonth','getLeaderboardsMonth')->name('getLeaderboardsMonth');
        Route::get('getLeaderboardsYear','getLeaderboardsYear')->name('getLeaderboardsYear');
    });

    Route::group(['controller' => 'UsersController', 'prefix' => 'users', 'as' => 'users.'], function (){
        Route::redirect('/','users/index');
        Route::get('index','index')->name('index');
        Route::get('getUsers','getUsers')->name('getUsers');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
    });

    Route::group(['controller' => 'SectionsController', 'prefix' => 'sections', 'as' => 'sections.'], function (){
        Route::redirect('/','sections/index');
        Route::get('index','index')->name('index');
        Route::get('getSections','getSections')->name('getSections');
        Route::get('bin','bin')->name('bin');
        Route::get('getSectionsDeleted','getSectionsDeleted')->name('getSectionsDeleted');
        Route::get('getSectionsList/{examId}','getSectionsList')->name('getSectionsList');
        Route::get('getSectionsExamList/{examId}','getSectionsExamList')->name('getSectionsExamList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ReviewersController', 'prefix' => 'reviewers', 'as' => 'reviewers.'], function (){
        Route::redirect('/','reviewers/index');
        Route::get('index','index')->name('index');
        Route::get('getReviewers','getReviewers')->name('getReviewers');
        Route::get('bin','bin')->name('bin');
        Route::get('getReviewersDeleted','getReviewersDeleted')->name('getReviewersDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'QuestionsController', 'prefix' => 'questions', 'as' => 'questions.'], function (){
        Route::redirect('/','questions/index');
        Route::get('index','index')->name('index');
        Route::get('getQuestions','getQuestions')->name('getQuestions');
        Route::get('bin','bin')->name('bin');
        Route::get('getQuestionsDeleted','getQuestionsDeleted')->name('getQuestionsDeleted');
        Route::get('getQuestionsSectionList/{sectionId}','getQuestionsSectionList')->name('getQuestionsSectionList');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'account/{id}', 'account')->name('account');
        Route::match(['get', 'post'],'changepassword/{id}', 'changepassword')->name('changepassword');
        Route::match(['get', 'post'],'orderPosition', 'orderPosition')->name('orderPosition');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'LessonsController', 'prefix' => 'lessons', 'as' => 'lessons.'], function (){
        Route::redirect('/','lessons/index');
        Route::get('index','index')->name('index');
        Route::get('getLessons','getLessons')->name('getLessons');
        Route::get('bin','bin')->name('bin');
        Route::get('getLessonsDeleted','getLessonsDeleted')->name('getLessonsDeleted');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'download/{id}', 'download')->name('download');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExamsController', 'prefix' => 'exams', 'as' => 'exams.'], function (){
        Route::redirect('/','exams/index');
        Route::get('index','index')->name('index');
        Route::get('getExams','getExams')->name('getExams');
        Route::get('bin','bin')->name('bin');
        Route::get('getExamsDeleted','getExamsDeleted')->name('getExamsDeleted');
        Route::get('getExam/{id}','getExam')->name('getExam');
        Route::get('practice','practice')->name('practice');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['delete', 'post'],'delete/{id}','delete')->name('delete');
        Route::match(['delete', 'post'],'restore/{id}','restore')->name('restore');
        Route::match(['delete', 'post'],'forceDelete/{id}','forceDelete')->name('forceDelete');
    });

    Route::group(['controller' => 'ExaminationsController', 'prefix' => 'examinations', 'as' => 'examinations.'], function (){
        Route::redirect('/','examinations/index');
        Route::get('index','index')->name('index');
        Route::get('getExaminations','getExaminations')->name('getExaminations');
        Route::get('today','today')->name('today');
        Route::get('getExaminationsToday','getExaminationsToday')->name('getExaminationsToday');
        Route::get('week','week')->name('week');
        Route::get('getExaminationsWeek','getExaminationsWeek')->name('getExaminationsWeek');
        Route::get('month','month')->name('month');
        Route::get('getExaminationsMonth','getExaminationsMonth')->name('getExaminationsMonth');
        Route::get('year','year')->name('year');
        Route::get('getExaminationsYear','getExaminationsYear')->name('getExaminationsYear');
        Route::match(['get', 'post'],'add', 'add')->name('add');
        Route::match(['get', 'post'],'edit/{id}', 'edit')->name('edit');
        Route::match(['get', 'post'],'view/{id}', 'view')->name('view');
        Route::match(['get', 'post'],'exam/{id}/{examId}', 'exam')->name('exam');
        Route::match(['get', 'post'],'release/{id}', 'release')->name('release');
        Route::get('counts/{userId}', 'counts')->name('counts');
        Route::get('getAnswersStatistics/{userId}', 'getAnswersStatistics')->name('getAnswersStatistics');
        Route::get('getAverage/{userId}', 'getAverage')->name('getAverage');
    });

    Route::group(['controller' => 'DocumentsController', 'prefix' => 'documents', 'as' => 'documents.'], function (){
        Route::redirect('/','documents/index');
        Route::get('index','index')->name('index');
        Route::get('getDocuments','getDocuments')->name('getDocuments');
        Route::get('bin','bin')->name('bin');
        Route::get('getDocumentsDeleted','getDocumentsDeleted')->name('getDocumentsDeleted');

app/Models/Examination.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Examination extends Model
{
    use HasFactory, SoftDeletes;

    protected $table = 'examinations';

    protected $fillable = [
        'user_id',
        'exam_id',
        'minutes',
        'month',
        'year',
        'start_date',
        'end_date',
        'total',
        'average',
        'is_released'
    ];

    protected function setMinutesAttribute($value){
        return $this->attributes['minutes'] = intval($value);
    }

    protected function setMonthAttribute($value){
        return $this->attributes['month'] = strtoupper($value);
    }

    public function Users(){
        return $this->belongsTo(User::class,'user_id','id');
    }

    public function Exams(){
        return $this->belongsTo(Exam::class,'exam_id','id');
    }

    public function Answers(){
        return $this->hasMany(Answer::class,'examination_id','id');
    }

}

resources/views/Admin/Examinations/exam.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')

    <?php
        $now = new \Moment\Moment('now', 'Asia/Manila');
        $interval = $now->from($examination->end_date);
        $endDate = new \Moment\Moment($examination->end_date, 'Asia/Manila');
        $disabled = ($endDate > $now)? null: 'disabled';
    ?>
    <script>
        var date = moment('{{strval($examination->end_date)}}');
        var examination_id = parseInt({{intval($examination->id)}});
        var user_id = parseInt({{intval(auth()->user()->id)}});
    </script>

    <div class="modal fade" id="modal" tabindex="-1" role="dialog" data-backdrop="static" aria-labelledby="modal" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered modal-xl" role="document">
            <div class="modal-content">
                @csrf
                <div class="modal-header d-flex justify-content-center align-items-center">
                    <h6 class="text-center m-0">Please Place You Face In The Camera, Wait Until You See A Blue Box</h6>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-sm-12 col-md-12 col-lg-12 d-flex justify-content-center align-items-center p-3">
                            <video id="video" width="400" height="400" style="position:relative;left:14.5em;top:0;width: 400px; height: 400px; border: 1px solid black;" autoplay></video>
                            <canvas id="canvas" width="400" height="400" style="position:relative;left:-14em;top:0;"></canvas>
                        </div>
                    </div>
                </div>
                <div class="modal-footer d-flex justify-content-center align-items-center">
                    <h6 class="text-center m-0">Please Hold Your Position</h6>
                </div>
            </div>
        </div>
    </div>

    <div class="toast fade show floating-timer" id="timer-container" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body" id="timer-body">
            <i class="fe fe-clock"></i>
            @if($endDate > $now)
                <?=(abs(intval($interval->getMinutes())).':'.(intval(60) - intval(date('s'))))?>
            @else
                --:--
            @endif
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <a href="{{route('admin.exams.practice')}}" id="toggle-modal" class="btn btn-secondary rounded-0" title="{{ucwords('Return')}}" turbo-links>Return</a>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 my-2">
            <div class="alert alert-light" role="alert">
                <h4 class="alert-heading text-uppercase">{{strtoupper($exam['exam'])}}</h4>
                <hr>
                <?php
                    $content = '';
                    $path = public_path($exam['content']);
                    $folder = \Illuminate\Support\Facades\File::isFile($path);
                    if($folder){
                        $content = file_get_contents($path);
                    }
                ?>
                <?=$content?>
            </div>
        </div>

        @foreach($exam['sections'] as $key => $section)

            <?php
                $content = '';
                $path = public_path($section['content']);
                $folder = \Illuminate\Support\Facades\File::isFile($path);
                if($folder){
                    $content = file_get_contents($path);
                }
            ?>

            <p class="h4 my-3 col-sm-12 col-md-12 col-lg-12 text-left">
                <a href="{{route('admin.reviewers.view',['id' => intval($section['reviewers']['id'])])}}" class="text-dark" target="_blank">{{strtoupper($section['reviewers']['reviewer'])}}</a>
            </p>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="alert alert-warning" role="alert">
                    <?=$content?>
                </div>
            </div>
            <?php
                $i = intval(1);
            ?>
            @foreach($section['questions'] as $key => $question)
                    <?php
                        $content = '';
                        $path = public_path($question['content']);
                        $folder = \Illuminate\Support\Facades\File::isFile($path);
                        if($folder){
                            $content = file_get_contents($path);
                        }
                    ?>
                <div class="col-sm-12 col-md-12 col-lg-12 my-2">
                    <div class="card shadow">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <strong class="card-title m-0" title="<?=strval($i);?>">
                                <?=intval($i)?>
                            </strong>
                            <?php
                                $letter = $answers->where('section_id', '=', intval($section['id']))
                                    ->where('question_id', '=', intval($question['id']))
                                    ->first();
                            ?>
                            <input type="text" class="w-25 form-control form-control-md rounded-0 answer" name="answer" placeholder="Answer" value="{{strtoupper(strval(@$letter['answer']))}}" data-section-id="{{intval($section['id'])}}" data-question-id="{{intval($question['id'])}}" {{$disabled}}>
                        </div>
                        <div class="card-body">
                            <?=$content?>
                        </div>
                    </div>
                </div>
                <?php $i++;?>
            @endforeach

        @endforeach

    </div>

    <script src="{{url('public/js/admin/examinations/exam.js')}}"></script>

@endsection

resources/views/Admin/Examinations/index.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <form class="row justify-content-center" id="form" method="post" enctype="multipart/form-data">
        @csrf
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">

        </div>

        <div class="col-sm-12 col-md-4 col-lg-4 mt-3">
            <label for="start-date">Start Date</label>
            <input type="date" name="start_date" class="form-control rounded-0" id="start-date" value="{{(new \Moment\Moment(null,'Asia/Manila'))->startOf('year')->format('Y-m-d')}}" title="{{ucwords('please fill out this field')}}" required>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-4 mt-3">
            <label for="end-date">End Date</label>
            <input type="date" name="end_date" class="form-control rounded-0" id="end-date" value="{{(new \Moment\Moment(null,'Asia/Manila'))->endOf('year')->format('Y-m-d')}}" title="{{ucwords('please fill out this field')}}" required>
        </div>
        <div class="col-sm-12 col-md-2 col-lg-2 mt-3">
            <label for="records">Records</label>
            <input type="number" name="records" class="form-control rounded-0" id="records" value="10000" min="10000" title="{{ucwords('please fill out this field')}}" placeholder="Records" required>
        </div>
        <div class="col-sm-12 col-md-2 col-lg-2 mt-3 d-flex justify-content-start align-items-end">
            <button type="submit" class="btn btn-primary rounded-0">Submit</button>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-body">
                    <div class="table-responsive p-1">
                        <table id="datatable" class="table table table-hover dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Examinee</th>
                                <th>Exam</th>
                                <th>Minutes</th>
                                <th>Month</th>
                                <th>Year</th>
                                <th>Total</th>
                                <th>Average</th>
                                <th>Is Active</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </form>

    <script src="{{url('public/js/admin/examinations/index.js')}}"></script>
@endsection

resources/views/Admin/Examinations/month.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end"></div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-body">
                    <div class="table-responsive p-1">
                        <table id="datatable" class="table table table-hover dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Examinee</th>
                                <th>Exam</th>
                                <th>Minutes</th>
                                <th>Month</th>
                                <th>Year</th>
                                <th>Total</th>
                                <th>Average</th>
                                <th>Is Active</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/examinations/month.js')}}"></script>
@endsection

resources/views/Admin/Examinations/today.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end"></div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-body">
                    <div class="table-responsive p-1">
                        <table id="datatable" class="table table table-hover dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Examinee</th>
                                <th>Exam</th>
                                <th>Minutes</th>
                                <th>Month</th>
                                <th>Year</th>
                                <th>Total</th>
                                <th>Average</th>
                                <th>Is Active</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/examinations/today.js')}}"></script>
@endsection

resources/views/Admin/Examinations/view.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')

    <script>
        var total = parseInt({{doubleval($exam['total'])}});
        var average =  parseFloat({{doubleval($examination->average)}}).toFixed(2);
    </script>

    <div class="toast fade show floating-timer" id="timer-container" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="toast-body d-flex justify-content-center align-items-center flex-column" id="timer-body">
            <div id="percircle" class="percircle blue">
            </div>
            <p class="h4" id="scores">
                {{doubleval($examination->total)}}/{{doubleval($exam['total'])}}
            </p>
            <small>
                <strong>{{strtoupper($examination->users->name)}}</strong>
            </small>
        </div>
    </div>

    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end">
            <a href="{{route('admin.exams.index')}}" id="toggle-modal" class="btn btn-secondary rounded-0" title="{{ucwords('Return')}}" turbo-links>Return</a>
        </div>

        <div class="col-sm-12 col-md-12 col-lg-12 my-2">
            <div class="alert alert-light" role="alert">
                <h4 class="alert-heading text-uppercase">{{strtoupper($exam['exam'])}}</h4>
                <hr>
                <?php
                    $content = '';
                    $path = public_path($exam['content']);
                    $folder = \Illuminate\Support\Facades\File::isFile($path);
                    if($folder){
                        $content = file_get_contents($path);
                    }

                    $isCorrect = [
                        'text-danger',
                        'text-success',
                    ];
                ?>
                <?=$content?>
            </div>
        </div>

        @foreach($exam['sections'] as $key => $section)

            <?php
                $content = '';
                $path = public_path($section['content']);
                $folder = \Illuminate\Support\Facades\File::isFile($path);
                if($folder){
                    $content = file_get_contents($path);
                }
            ?>

            <p class="h4 my-3 col-sm-12 col-md-12 col-lg-12 text-left">
                <a href="{{route('admin.reviewers.view',['id' => intval($section['reviewers']['id'])])}}" class="text-dark" target="_blank">{{strtoupper($section['reviewers']['reviewer'])}}</a>
            </p>
            <div class="col-sm-12 col-md-12 col-lg-12">
                <div class="alert alert-warning" role="alert">
                    <?=$content?>
                </div>
            </div>
            <?php
            $i = intval(1);
            ?>
            @foreach($section['questions'] as $key => $question)
                <?php
                    $content = '';
                    $path = public_path($question['content']);
                    $folder = \Illuminate\Support\Facades\File::isFile($path);
                    if($folder){
                        $content = file_get_contents($path);
                }
                ?>
                <div class="col-sm-12 col-md-12 col-lg-12 my-2">
                    <div class="card shadow">
                        <div class="card-header d-flex justify-content-between align-items-center">
                            <?php
                                $letter = $answers->where('section_id', '=', intval($section['id']))
                                    ->where('question_id', '=', intval($question['id']))
                                    ->first();
                            ?>
                            <strong class="card-title m-0 <?=($isCorrect[intval(@$letter['is_correct'])])?>" title="The Answer Is <?=strtoupper($question['answer']);?>" style="cursor:pointer !important;">
                                <?=intval($i)?>
                            </strong>
                            <div class="input-group w-25">
                                <input type="text" class="form-control form-control-md rounded-0 answer" name="answer" placeholder="Answer" value="{{strtoupper(strval(@$letter['answer']))}}" data-section-id="{{intval($section['id'])}}" data-question-id="{{intval($question['id'])}}" disabled>
                                @if(!empty($letter))
                                    @if(boolval($letter['is_correct']))
                                        <div class="input-group-append rounded-0">
                                            <button class="btn btn-success rounded-0 px-2 py-0 d-flex justify-content-center align-items-center text-white is-correct" type="button" data-id="{{intval($letter['id'])}}" data-is-correct="0">
                                                <i class="fe fe-check" style="font-size: 20px !important;"></i>
                                            </button>
                                        </div>
                                    @else
                                        <div class="input-group-append rounded-0">
                                            <button class="btn btn-danger rounded-0 px-2 py-0 d-flex justify-content-center align-items-center text-white is-correct" type="button" data-id="{{intval($letter['id'])}}" data-is-correct="1">
                                                <i class="fe fe-x" style="font-size: 20px !important;"></i>
                                            </button>
                                        </div>
                                    @endif
                                @endif
                            </div>
                        </div>
                        <div class="card-body">
                            <?=$content?>
                        </div>
                    </div>
                </div>
                <?php $i++;?>
            @endforeach

        @endforeach

    </div>

    <script src="{{url('public/js/admin/examinations/view.js')}}"></script>
@endsection

resources/views/Admin/Examinations/week.blade.php
@extends('layout.admin')
@section('title', ucwords(explode('.', Route::currentRouteName())[0]))
@section('content')
    <div class="row justify-content-center">
        <div class="col-sm-12 col-md-8 col-lg-9">
            <h3 class="page-title">{{ucwords(explode('.', Route::currentRouteName())[1])}}</h3>
        </div>
        <div class="col-sm-12 col-md-4 col-lg-3 d-flex justify-content-end align-items-end"></div>

        <div class="col-sm-12 col-md-12 col-lg-12 mt-3">
            <div class="card shadow">
                <div class="card-body">
                    <div class="table-responsive p-1">
                        <table id="datatable" class="table table table-hover dt-responsive nowrap w-100">
                            <thead>
                            <tr>
                                <th>No</th>
                                <th>Examinee</th>
                                <th>Exam</th>
                                <th>Minutes</th>
                                <th>Month</th>
                                <th>Year</th>
                                <th>Total</th>
                                <th>Average</th>
                                <th>Is Active</th>
                                <th>Updated At</th>
                                <th>Options</th>
                            </tr>
                            </thead>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="{{url('public/js/admin/examinations/week.js')}}"></script>
@endsection